// <auto-generated />
namespace MATO.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPaymentType_IdIntas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPaymentType_IdIntas));
        
        string IMigrationMetadata.Id
        {
            get { return "202009211404560_AddPaymentType_IdIntas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
